<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.10.0 on win32)" generated="20211030 04:12:25.364" rpa="false" schemaversion="2">
<suite id="s1" name="Test Case" source="c:\Users\t01484\Desktop\t01484\CURSOS\Prime Experts - Turma 4\Prime-Experts-Turma-4\MY SANDBOX\Test Case.robot">
<test id="s1-t1" name="Op">
<status status="FAIL" starttime="20211030 04:12:25.452" endtime="20211030 04:12:25.454">Test case contains no keywords.</status>
</test>
<status status="FAIL" starttime="20211030 04:12:25.374" endtime="20211030 04:12:25.456"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Case">Test Case</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211030 04:12:25.355" level="ERROR">Error in file 'c:\Users\t01484\Desktop\t01484\CURSOS\Prime Experts - Turma 4\Prime-Experts-Turma-4\MY SANDBOX\Test Case.robot' on line 2: Non-existing setting ''.</msg>
<msg timestamp="20211030 04:12:25.355" level="ERROR">Error in file 'c:\Users\t01484\Desktop\t01484\CURSOS\Prime Experts - Turma 4\Prime-Experts-Turma-4\MY SANDBOX\Test Case.robot' on line 3: Non-existing setting ''.</msg>
</errors>
</robot>
